A = B = C = D = 0

comandos = {}
comandos['00'] = None
comandos['01'] = { 'comando' : b"0101", 'sistema_numerico' : None, 'bytes': 4, 'conversor' : None, 'unidade' : None, 'descricao' : "Monitorar o status desde que os DTCs foram removidos" }
comandos['03'] = { 'comando' : b"0103", 'sistema_numerico' : None, 'bytes': 2, 'conversor' : None, 'unidade' : None, 'descricao' : "DTC que causou armazenamento no Freeze-Frame" }
comandos['04'] = { 'comando' : b"0104", 'sistema_numerico' : None, 'bytes': 2, 'conversor' : None, 'unidade' : None, 'descricao' : "Status do sistema de combustível" }
comandos['02'] = { 'comando' : b"0102", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [A/2.55], 'unidade' : ['%'], 'descricao' : "Carga calculada do motor" }
comandos['05'] = { 'comando' : b"0105", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [A-40], 'unidade' : ['°C'], 'descricao' : "Temperatura do refrigerante do motor" }
comandos['06'] = { 'comando' : b"0106", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [(A/1.28)-100], 'unidade' : ['%'], 'descricao' : "Calibração de combustível a curto prazo - Banco 1" }
comandos['07'] = { 'comando' : b"0107", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [(A/1.28)-100], 'unidade' : ['%'], 'descricao' : "Calibração de combustível a longo prazo - Banco 1" }
comandos['08'] = { 'comando' : b"0108", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [(A/1.28)-100], 'unidade' : ['%'], 'descricao' : "Calibração de combustível a curto prazo - Banco 2" }
comandos['09'] = { 'comando' : b"0109", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [(A/1.28)-100], 'unidade' : ['%'], 'descricao' : "Calibração de combustível a longo prazo - Banco 2" }
comandos['0A'] = { 'comando' : b"010A", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [3*A], 'unidade' : ['kPa'], 'descricao' : "Pressão do combustível" }
comandos['0B'] = { 'comando' : b"010B", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [A], 'unidade' : ['kPa'], 'descricao' : "Pressão absoluta do coletor de admissão" }
comandos['0C'] = { 'comando' : b"010C", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [(256*A+B)/4], 'unidade' : ['rpm'], 'descricao' : "RPM " }
comandos['0D'] = { 'comando' : b"010D", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [A], 'unidade' : ['km/h'], 'descricao' : "Velocidade do veiculo" }
comandos['0E'] = { 'comando' : b"010E", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [(A/2)-64], 'unidade' : ['°'], 'descricao' : "Avanço de tempo" }
comandos['0F'] = { 'comando' : b"010F", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [A-40], 'unidade' : ['°C'], 'descricao' : "Temperatura do ar de admissão" }
comandos['10'] = { 'comando' : b"0110", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [(256*A+B)/100], 'unidade' : ['gramas/s'], 'descricao' : "Taxa de fluxo de ar de MAF" }
comandos['11'] = { 'comando' : b"0111", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [A/2.55], 'unidade' : ['%'], 'descricao' : "Posição do acelerador" }
comandos['12'] = { 'comando' : b"0112", 'sistema_numerico' : None, 'bytes': 1, 'conversor' : None, 'unidade' : None, 'descricao' : "Estado do ar secundário com comando" }
comandos['13'] = { 'comando' : b"0113", 'sistema_numerico' : None, 'bytes': 1, 'conversor' : None, 'unidade' : None, 'descricao' : "Sensores de oxigênio presentes (em 2 bancos)" }
comandos['14'] = { 'comando' : b"0114", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [A/200, (B/1.28)-100], 'unidade' : ['V', '%'], 'descricao' : "Sensor de oxigênio 1" }
comandos['15'] = { 'comando' : b"0115", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [A/200, (B/1.28)-100], 'unidade' : ['V', '%'], 'descricao' : "Sensor de oxigênio 2" }
comandos['16'] = { 'comando' : b"0116", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [A/200, (B/1.28)-100], 'unidade' : ['V', '%'], 'descricao' : "Sensor de oxigênio 3" }
comandos['17'] = { 'comando' : b"0117", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [A/200, (B/1.28)-100], 'unidade' : ['V', '%'], 'descricao' : "Sensor de oxigênio 4" }
comandos['18'] = { 'comando' : b"0118", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [A/200, (B/1.28)-100], 'unidade' : ['V', '%'], 'descricao' : "Sensor de oxigênio 5" }
comandos['19'] = { 'comando' : b"0119", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [A/200, (B/1.28)-100], 'unidade' : ['V', '%'], 'descricao' : "Sensor de oxigênio 6" }
comandos['1A'] = { 'comando' : b"011A", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [A/200, (B/1.28)-100], 'unidade' : ['V', '%'], 'descricao' : "Sensor de oxigênio 7" }
comandos['1B'] = { 'comando' : b"011B", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [A/200, (B/1.28)-100], 'unidade' : ['V', '%'], 'descricao' : "Sensor de oxigênio 8" }
comandos['1C'] = { 'comando' : b"011C", 'sistema_numerico' : None, 'bytes': 1, 'conversor' : None, 'unidade' : None, 'descricao' : "Padrões OBD que este veículo está em conformidade " }
comandos['1D'] = { 'comando' : b"011D", 'sistema_numerico' : None, 'bytes': 1, 'conversor' : None, 'unidade' : None, 'descricao' : "Sensores de oxigênio presentes (em 4 bancos)" }
comandos['1E'] = { 'comando' : b"011E", 'sistema_numerico' : None, 'bytes': 1, 'conversor' : None, 'unidade' : None, 'descricao' : "Status de entrada auxiliar" }
comandos['1F'] = { 'comando' : b"011F", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [256*A+B], 'unidade' : ['segundos'], 'descricao' : "Tempo de execução desde o início do motor" }
comandos['20'] = None
comandos['21'] = { 'comando' : b"0121", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [256*A+B], 'unidade' : ['km'], 'descricao' : "Distância percorrida com a luz indicadora de mau funcionamento (MIL) em" }
comandos['22'] = { 'comando' : b"0122", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [0.079*(256*A+B)], 'unidade' : ['kPa'], 'descricao' : "Pressão do combustível (relativo ao vácuo do coletor)" }
comandos['23'] = { 'comando' : b"0123", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [10*(256*A+B)], 'unidade' : ['kPa'], 'descricao' : "Pressão do jato de combustível" }
comandos['24'] = { 'comando' : b"0124", 'sistema_numerico' : 'dec', 'bytes': 4, 'conversor' : [(2/65536)*(256*A+B), (8/65536)*(256*C+D)], 'unidade' : ['razão', 'V'], 'descricao' : "Sensor de oxigênio 1" }
comandos['25'] = { 'comando' : b"0125", 'sistema_numerico' : 'dec', 'bytes': 4, 'conversor' : [(2/65536)*(256*A+B), (8/65536)*(256*C+D)], 'unidade' : ['razão', 'V'], 'descricao' : "Sensor de oxigênio 2" }
comandos['26'] = { 'comando' : b"0126", 'sistema_numerico' : 'dec', 'bytes': 4, 'conversor' : [(2/65536)*(256*A+B), (8/65536)*(256*C+D)], 'unidade' : ['razão', 'V'], 'descricao' : "Sensor de oxigênio 3" }
comandos['27'] = { 'comando' : b"0127", 'sistema_numerico' : 'dec', 'bytes': 4, 'conversor' : [(2/65536)*(256*A+B), (8/65536)*(256*C+D)], 'unidade' : ['razão', 'V'], 'descricao' : "Sensor de oxigênio 4" }
comandos['28'] = { 'comando' : b"0128", 'sistema_numerico' : 'dec', 'bytes': 4, 'conversor' : [(2/65536)*(256*A+B), (8/65536)*(256*C+D)], 'unidade' : ['razão', 'V'], 'descricao' : "Sensor de oxigênio 5" }
comandos['29'] = { 'comando' : b"0129", 'sistema_numerico' : 'dec', 'bytes': 4, 'conversor' : [(2/65536)*(256*A+B), (8/65536)*(256*C+D)], 'unidade' : ['razão', 'V'], 'descricao' : "Sensor de oxigênio 6" }
comandos['2A'] = { 'comando' : b"012A", 'sistema_numerico' : 'dec', 'bytes': 4, 'conversor' : [(2/65536)*(256*A+B), (8/65536)*(256*C+D)], 'unidade' : ['razão', 'V'], 'descricao' : "Sensor de oxigênio 7" }
comandos['2B'] = { 'comando' : b"012B", 'sistema_numerico' : 'dec', 'bytes': 4, 'conversor' : [(2/65536)*(256*A+B), (8/65536)*(256*C+D)], 'unidade' : ['razão', 'V'], 'descricao' : "Sensor de oxigênio 8" }
comandos['2C'] = { 'comando' : b"012C", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [A/2.55], 'unidade' : ['%'], 'descricao' : "EGR comandado" }
comandos['2D'] = { 'comando' : b"012D", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [(A/1.28)-100], 'unidade' : ['%'], 'descricao' : "Erro EGR" }
comandos['2E'] = { 'comando' : b"012E", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [[A/2.55]], 'unidade' : ['%'], 'descricao' : "Purga evaporativa com comando" }
comandos['2F'] = { 'comando' : b"012F", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [[A/2.55]], 'unidade' : ['%'], 'descricao' : "Entrada do nível do tanque de combustível" }
comandos['30'] = { 'comando' : b"0130", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [A], 'unidade' : ['quantidade'], 'descricao' : "Warm-ups desde códigos apagados" }
comandos['31'] = { 'comando' : b"0131", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [256*A+B], 'unidade' : ['km'], 'descricao' : "Distância percorrida desde que os códigos foram limpos" }
comandos['32'] = { 'comando' : b"0132", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [(256*A+B)/4], 'unidade' : ['Pa'], 'descricao' : "Evap. Pressão de vapor do sistema" }
comandos['33'] = { 'comando' : b"0133", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [A], 'unidade' : ['kPa'], 'descricao' : "Pressão Barométrica Absoluta" }
comandos['34'] = { 'comando' : b"0134", 'sistema_numerico' : 'dec', 'bytes': 4, 'conversor' : [(2/65536)*(256*A+B), (256*C+D)-128], 'unidade' : ['razão', 'mA'], 'descricao' : "Sensor de oxigênio 1" }
comandos['35'] = { 'comando' : b"0135", 'sistema_numerico' : 'dec', 'bytes': 4, 'conversor' : [(2/65536)*(256*A+B), (256*C+D)-128], 'unidade' : ['razão', 'mA'], 'descricao' : "Sensor de oxigênio 2" }
comandos['36'] = { 'comando' : b"0136", 'sistema_numerico' : 'dec', 'bytes': 4, 'conversor' : [(2/65536)*(256*A+B), (256*C+D)-128], 'unidade' : ['razão', 'mA'], 'descricao' : "Sensor de oxigênio 3" }
comandos['37'] = { 'comando' : b"0137", 'sistema_numerico' : 'dec', 'bytes': 4, 'conversor' : [(2/65536)*(256*A+B), (256*C+D)-128], 'unidade' : ['razão', 'mA'], 'descricao' : "Sensor de oxigênio 4" }
comandos['38'] = { 'comando' : b"0138", 'sistema_numerico' : 'dec', 'bytes': 4, 'conversor' : [(2/65536)*(256*A+B), (256*C+D)-128], 'unidade' : ['razão', 'mA'], 'descricao' : "Sensor de oxigênio 5" }
comandos['39'] = { 'comando' : b"0139", 'sistema_numerico' : 'dec', 'bytes': 4, 'conversor' : [(2/65536)*(256*A+B), (256*C+D)-128], 'unidade' : ['razão', 'mA'], 'descricao' : "Sensor de oxigênio 6" }
comandos['3A'] = { 'comando' : b"013A", 'sistema_numerico' : 'dec', 'bytes': 4, 'conversor' : [(2/65536)*(256*A+B), (256*C+D)-128], 'unidade' : ['razão', 'mA'], 'descricao' : "Sensor de oxigênio 7" }
comandos['3B'] = { 'comando' : b"013B", 'sistema_numerico' : 'dec', 'bytes': 4, 'conversor' : [(2/65536)*(256*A+B), (256*C+D)-128], 'unidade' : ['razão', 'mA'], 'descricao' : "Sensor de oxigênio 8" }
comandos['3C'] = { 'comando' : b"013C", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [((256*A+B)/10)-40], 'unidade' : ['°C'], 'descricao' : "Temperatura do catalisador: Banco 1, Sensor 1" }
comandos['3D'] = { 'comando' : b"013D", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [((256*A+B)/10)-40], 'unidade' : ['°C'], 'descricao' : "Temperatura do catalisador: Banco 2, Sensor 1" }
comandos['3E'] = { 'comando' : b"013E", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [((256*A+B)/10)-40], 'unidade' : ['°C'], 'descricao' : "Temperatura do catalisador: Banco 1, Sensor 2" }
comandos['3F'] = { 'comando' : b"013F", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [((256*A+B)/10)-40], 'unidade' : ['°C'], 'descricao' : "Temperatura do catalisador: Banco 2, Sensor 2" }
comandos['40'] = None
comandos['41'] = { 'comando' : b"0141", 'sistema_numerico' : None, 'bytes': 4, 'conversor' : None, 'unidade' : None, 'descricao' : "Monitorar este status do ciclo da unidade" }
comandos['42'] = { 'comando' : b"0142", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [(256*A+B)/1000], 'unidade' : ['V'], 'descricao' : "Tensão do módulo de controle" }
comandos['43'] = { 'comando' : b"0143", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [(256*A+B)/2.55], 'unidade' : ['%'], 'descricao' : "Valor de carga absoluta" }
comandos['44'] = { 'comando' : b"0144", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [(256*A+B)*(2/65536)], 'unidade' : ['razão'], 'descricao' : "Taxa de equivalência com comando de combustível-ar" }
comandos['45'] = { 'comando' : b"0145", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [A/2.55], 'unidade' : ['%'], 'descricao' : "Posição relativa do acelerador" }
comandos['46'] = { 'comando' : b"0146", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [A-40], 'unidade' : ['°C'], 'descricao' : "Temperatura do ar ambiente" }
comandos['47'] = { 'comando' : b"0147", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [A/2.55], 'unidade' : ['%'], 'descricao' : "Posição absoluta do acelerador B" }
comandos['48'] = { 'comando' : b"0148", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [A/2.55], 'unidade' : ['%'], 'descricao' : "Posição absoluta do acelerador C" }
comandos['49'] = { 'comando' : b"0149", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [A/2.55], 'unidade' : ['%'], 'descricao' : "Posição do pedal do acelerador D" }
comandos['4A'] = { 'comando' : b"014A", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [A/2.55], 'unidade' : ['%'], 'descricao' : "Posição do pedal do acelerador E" }
comandos['4B'] = { 'comando' : b"014B", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [A/2.55], 'unidade' : ['%'], 'descricao' : "Posição do pedal do acelerador F" }
comandos['4C'] = { 'comando' : b"014C", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [A/2.55], 'unidade' : ['%'], 'descricao' : "Atuador de acelerador com comando" }
comandos['4D'] = { 'comando' : b"014D", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [256*A+B], 'unidade' : ['minutos'], 'descricao' : "Tempo de execução com MIL ligado" }
comandos['4E'] = { 'comando' : b"014E", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [256*A+B], 'unidade' : ['minutos'], 'descricao' : "Tempo desde que os códigos de problemas foram limpos" }
comandos['4F'] = { 'comando' : b"014F", 'sistema_numerico' : 'dec', 'bytes': 4, 'conversor' : [A, B, C, D*10], 'unidade' : ['razão', 'V', 'mA', 'kPa'], 'descricao' : "Valor máximo para a relação de equivalência de combustível-ar, tensão do sensor de oxigênio, corrente do sensor de oxigênio e pressão absoluta do colector de admissão" }
comandos['50'] = { 'comando' : b"0150", 'sistema_numerico' : 'dec', 'bytes': 4, 'conversor' : [A*10, B, C], 'unidade' : ['g/s', 'g/s', 'g/s'], 'descricao' : "Valor máximo para o caudal do ar a partir do sensor de fluxo de ar em massa" }
comandos['51'] = { 'comando' : b"0151", 'sistema_numerico' : None, 'bytes': 1, 'conversor' : None, 'unidade' : None, 'descricao' : "Tipo de combustível atualmente utilizado pelo veículo" }
comandos['52'] = { 'comando' : b"0152", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [A/2.55], 'unidade' : ['%'], 'descricao' : "Percentual de etanol no combustível" }
comandos['53'] = { 'comando' : b"0153", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [(256*A+B)/200], 'unidade' : ['kPa'], 'descricao' : "Pressão absoluta de vapor no sistema Evap" }
comandos['54'] = { 'comando' : b"0154", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [(256*A+B)-32767], 'unidade' : ['Pa'], 'descricao' : "Pressão de vapor no sistema Evap" }
comandos['55'] = { 'comando' : b"0155", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [A/1.28-100, B/1.28-100], 'unidade' : ['%', '%'], 'descricao' : "Aparelho de sensor de oxigênio secundário de curto prazo" }
comandos['56'] = { 'comando' : b"0156", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [A/1.28-100, B/1.28-100], 'unidade' : ['%', '%'], 'descricao' : "Aparelho de sensor de oxigênio secundário de longo prazo" }
comandos['57'] = { 'comando' : b"0157", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [A/1.28-100, B/1.28-100], 'unidade' : ['%', '%'], 'descricao' : "Aparelho de sensor de oxigênio secundário de curto prazo" }
comandos['58'] = { 'comando' : b"0158", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [A/1.28-100, B/1.28-100], 'unidade' : ['%', '%'], 'descricao' : "Aparelho de sensor de oxigênio secundário de longa duração" }
comandos['59'] = { 'comando' : b"0159", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [10*(256*A+B)], 'unidade' : ['kPa'], 'descricao' : "Pressão absoluta do combustível ferroviário" }
comandos['5A'] = { 'comando' : b"015A", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [A/2.55], 'unidade' : ['%'], 'descricao' : "Posição relativa do pedal do acelerador" }
comandos['5B'] = { 'comando' : b"015B", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [A/2.55], 'unidade' : ['%'], 'descricao' : "Vida útil restante da bateria híbrida" }
comandos['5C'] = { 'comando' : b"015C", 'sistema_numerico' : 'dec', 'bytes': 1, 'conversor' : [A-40], 'unidade' : ['°C'], 'descricao' : "Temperatura do óleo do motor" }
comandos['5D'] = { 'comando' : b"015D", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [((256*A+B)/128)-210], 'unidade' : ['°'], 'descricao' : "Tempo de injeção de combustível" }
comandos['5E'] = { 'comando' : b"015E", 'sistema_numerico' : 'dec', 'bytes': 2, 'conversor' : [(256*A+B)/20], 'unidade' : ['L/h'], 'descricao' : "Taxa de combustível do motor" }
comandos['5F'] = { 'comando' : b"015F", 'sistema_numerico' : None, 'bytes': 1, 'conversor' : None, 'unidade' : None, 'descricao' : "Requisitos de emissão para os quais o veículo foi projetado" }

print(comandos['5F']['descricao'])